// Poesías de ejemplo
const poesias = {
    poesia1: "No te quedes inmóvil/ al borde del camino/ no congeles el júbilo/ no quieras con desgana/ no te salves ahora/ ni nunca/ no te salves/ no te llenes de calma/ no reserves del mundo/ sólo un rincón tranquilo/ no dejes caer los párpados/ pesados como juicios/ no te quedes sin labios/ no te duermas sin sueño/ no te pienses sin sangre/ no te juzgues sin tiempo pero si/ pese a todo/ no puedes evitarlo/ y congelas el júbilo/ y quieres con desgana/ y te salvas ahora/ y te llenas de calma/ y reservas del mundo/ sólo un rincón tranquilo/ y dejas caer los párpados/ pesados como juicios/ y te secas sin labios/ y te duermes sin sueño/ y te piensas sin sangre/ y te juzgas sin tiempo/ y te quedas inmóvil/ al borde del camino/ y te salvas/entonces / no te quedes conmigo.",
    poesia2: "Si la esmeralda se opacara,/ si el oro perdiera su color,/ entonces, se acabaría/ nuestro amor.Si el sol no calentara,/ si la luna no existiera,/ entonces, no tendría/ sentido vivir en esta tierra/ como tampoco tendría sentido/ vivir sin mi vida,/ la mujer de mis sueños,/ la que me da la alegría…Si el mundo no girara/ o el tiempo no existiese,/ entonces, jamás moriría/ Jamás morirías/ tampoco nuestro amor…/ pero el tiempo no es necesario/ nuestro amor es eterno/ no necesitamos del sol/ de la luna o los astros/ para seguir amándonos…Si la vida fuera otra/ y la muerte llegase/ entonces, te amaría/ hoy, mañana…/ por siempre…/ todavía.",
    poesia3: "No cabe duda. Esta es mi casa/ aquí sucedo, aquí/ me engaño inmensamente./ Esta es mi casa detenida en el tiempo.Llega el otoño y me defiende,/ la primavera y me condena./ Tengo millones de huéspedes/ que ríen y comen,/ copulan y duermen,/ juegan y piensan,/ millones de huéspedes que se aburren/ y tienen pesadillas y ataques de nervios.No cabe duda. Ésta es mi casa./ Todos los perros y campanarios/ pasan frente a ella./ Pero a mi casa la azotan los rayos/ y un día se va a partir en dos.Y yo no sabré dónde guarecerme/ porque todas las puertas dan afuera del mundo.",
    poesia4: "Compañera/ usted sabe/ puede contar/ conmigo/ no hasta dos/ o hasta diez/ sino contar/ conmigo si alguna vez/ advierte/ que la miro a los ojos/ y una veta de amor/ reconoce en los míos/ no alerte sus fusiles/ ni piense qué delirio/ a pesar de la veta/ o tal vez porque existe/ usted puede contar/ conmigo  si otras veces/ me encuentra/ huraño sin motivo/ no piense qué flojera/ igual puede contar/ conmigo pero hagamos un trato/ yo quisiera contar/ con ustedes tan lindo/ saber que usted existe/ uno se siente vivo/ y cuando digo esto/ quiero decir contar/ aunque sea hasta dos/ aunque sea hasta cinco/ no ya para que acuda/ presurosa en mi auxilio/ sino para saber/ a ciencia cierta/ que usted sabe que puede/ contar conmigo.",
    poesia5: "Porque te tengo y no/ porque te pienso/ porque la noche está de ojos abiertos/ porque la noche pasa y digo amor/ porque has venido a recoger tu imagen/ y eres mejor que todas tus imágenes/ porque eres linda desde el pie hasta el alma/ porque eres buena desde el alma a mí/ porque te escondes dulce en el orgullo/ pequeña y dulce/ corazón coraza porque eres mía/ porque no eres mía/ porque te miro y muero/ y peor que muero/ si no te miro amor/ si no te miro porque tú siempre existes dondequiera/ pero existes mejor donde te quiero/ porque tu boca es sangre/ y tienes frío/ tengo que amarte amor/ tengo que amarte/ aunque ésta herida duela como dos/ aunque te busque y no te encuentre/ y aunque la noche pase/ y yo te tenga/ y no.",
    poesia6: "Mi táctica es/ Mirarte/ Aprender como sos/ Quererte como sos/Mi táctica es/ Hablarte/ Y escucharte/ Construir con palabras/ Un puente indestructible/Mi táctica es/ Quedarme en tu recuerdo/ No sé cómo ni sé/ Con qué pretexto/ Pero quedarme en vos Mi táctica es/ Ser franco/ Y saber que sos franca/ Y que no nos vendamos/ Simulacros/ Para que entre los dos/ No haya telón/ Ni abismosMi estrategia es/ En cambio/ Más profunda y más/ Simple Mi estrategia es/ Que un día cualquiera/ No sé cómo ni sé/ Con qué pretexto/ Por fin me necesites",
    poesia7: "Tus manos son mi caricia/ mis acordes cotidianos/ te quiero porque tus manos/ trabajan por la justicia.Si te quiero es porque sos/ mi amor mi cómplice y todo/ y en la calle codo a codo/ somos mucho más que dos Tus ojos son mi conjuro/ contra la mala jornada/ te quiero por tu mirada/ que mira y siembra futuro Tu boca que es tuya y mía/ tu boca no se equivoca/ te quiero porque tu boca/ sabe gritar rebeldía Si te quiero es porque sos/ mi amor mi cómplice y todo/ y en la calle codo a codo/ somos mucho más que dos Y por tu rostro sincero/ y tu paso vagabundo/ y tu llanto por el mundo/ porque sos pueblo te quiero Y porque amor no es aureola/ ni cándida moraleja/ y porque somos pareja/ que sabe que no está sola Te quiero en mi paraíso/ es decir que en mi país/ la gente viva feliz/ aunque no tenga permiso Si te quiero es porque sos/ mi amor mi cómplice y todo/ y en la calle codo a codo/ somos mucho más que dos.",
    poesia8: "Defender la alegría como una trinchera/ defenderla del escándalo y la rutina/ de la miseria y los miserables/ de las ausencias transitorias/ y las definitivasDefender la alegría como un principio/ defenderla del pasmo y las pesadillas/ de los neutrales y de los neutrones/ de las dulces infamias/ y los graves diagnósticosDefender la alegría como una bandera/ defenderla del rayo y la melancolía/ de los ingenuos y de los canallas/ de la retórica y los paros cardiacos/ de las endemias y las academias Defender la alegría como un destino/ defenderla del fuego y de los bomberos/ de los suicidas y los homicidas/ de las vacaciones y del agobio/ de la obligación de estar alegres Defender la alegría como una certeza/ defenderla del óxido y de la roña/ de la famosa pátina del tiempo/ del relente y del oportunismo/ de los proxenetas de la risa Defender la alegría como un derecho/ defenderla de dios y del invierno/ de las mayúsculas y de la muerte/ de los apellidos y las lástimas/ del azar/ y también de la alegría.",
    poesia9: "No lo creo todavía/ estás llegando a mi lado/ y la noche es un puñado/ de estrellas y de alegría Palpo gusto escucho y veo/ tu rostro tu paso largo/ tus manos y sin embargo/ todavía no lo creo Tu regreso tiene tanto/ que ver contigo y conmigo/ que por cábala lo digo/ y por las dudas lo canto Nadie nunca te reemplaza/ y las cosas más triviales/ se vuelven fundamentales/ porque estás llegando a casa Sin embargo todavía/ dudo de esta buena suerte/ porque el cielo de tenerte/ me parece fantasía Pero venís y es seguro/ y venís con tu mirada/ y por eso tu llegada/ hace mágico el futuro Y aunque no siempre he entendido/ mis culpas y mis fracasos/ en cambio sé que en tus brazos/ el mundo tiene sentido Y si beso la osadía/ y el misterio de tus labios/ no habrá dudas ni resabios/ te querré más/ todavía.",
    poesia10: "Es una lástima que no estés conmigo/ cuando miro el reloj y son las cuatro/ y acabo la planilla y pienso diez minutos/ y estiro las piernas como todas las tardes/ y hago así con los hombros para aflojar la espalda/ y me doblo los dedos y les saco mentiras. Es una lástima que no estés conmigo/ cuando miro el reloj y son las cinco/ y soy una manija que calcula intereses/ o dos manos que saltan sobre cuarenta teclas/ o un oído que escucha como ladra el teléfono/ o un tipo que hace números y les saca verdades. Es una lástima que no estés conmigo/ cuando miro el reloj y son las seis./ Podrías acercarte de sorpresa/ y decirme ¿Qué tal? y quedaríamos/ yo con la mancha roja de tus labios/ tú con el tizne azul de mi carbónico.",
 
};

function mostrarPoesia(poesiaId) {
    document.getElementById("titulo-poesia").innerText = poesiaId.replace("poesia", "Título de Poesía ");
    document.getElementById("texto-poesia").innerText = poesias[poesiaId];
    document.getElementById("formulario").classList.remove("oculto");
    ajustarAltura(document.getElementById("texto-poesia")); // Ajustar altura al mostrar
}

function cerrarFormulario() {
    document.getElementById("formulario").classList.add("oculto");
}

function ajustarAltura(textarea) {
    textarea.style.height = 'auto'; // Restablece la altura a 'auto' para calcular correctamente
    textarea.style.height = textarea.scrollHeight + 'px'; // Ajusta la altura al contenido

}

function leerTexto(id) {
    const texto = document.getElementById(id).innerText;
    const speech = new SpeechSynthesisUtterance(texto);
    window.speechSynthesis.speak(speech);
}